
run:
  modules-download-mode: vendor

linters-settings:
  cyclop:
    max-complexity: 15
    package-average: 10
    skip-tests: true
  govet:
    check-shadowing: true
  lll:
    line-length: 120
    tab-width: 4

linters:
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - errname
    - exhaustive
    - exhaustivestruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    # - golint  # deprecated
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    # - interfacer  # deprecated
    - lll
    - makezero
    # - maligned  # deprecated
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - paralleltest
    - predeclared
    - revive
    # - scopelint  # deprecated
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - varcheck
    - wastedassign
    - whitespace
  disabled:
    - durationcheck     # No duration types used
    - gochecknoglobals  # This can sometimes be needed
    - gomnd             # False Positives on length checks
    - nlreturn          # Style; can result in oddly spaced code with single returns
    - prealloc          # Premature optimization; can result in false positives
    - promlinter        # Prometheus isn't used
    - rowserrcheck      # No DB/SQL in this project
    - sqlclosecheck     # No DB/SQL in this project
    - unparam           # Style; personal preference it to assign names even if not used
    - wrapcheck         # Returning errors from external packages is fine
    - wsl               # Style; personal preference clashes with linter

issues:
  exclude-rules:
    - path: _test\.go
      # Turn off the following linters for all test files
      linters:
        - dupl
        - exhaustivestruct
        - lll
        - funlen
        - errcheck
        - goerr113
        - goconst
        - gofumpt